In [1]:
import pandas as pd
import numpy as np

1.Avg

In [25]:
data = np.random.random(size=(10,5))
df = pd.DataFrame(data)
df[df > 0.3].mean(axis = 1)

0    0.486364
1    0.599587
2    0.663922
3    0.444551
4    0.648213
5    0.622565
6    0.550701
7    0.571266
8    0.640118
9    0.754561
dtype: float64

2.Production

In [142]:
wells_info_df = pd.read_csv('wells_info.csv')
wells_info_df

,API,PermitDate,SpudDate,CompletionDate,FirstProductionDate,operatorNameIHS,formation,BasinName,StateName,CountyName,LatWGS84,LonWGS84,BottomHoleLatitude,BottomHoleLongitude,LATERAL_LENGTH_BLEND,PROP_PER_FOOT,WATER_PER_FOOT
0,5005072170100,2014-05-06,2014-05-06,2014-12-02,2014-11-01 00:00:00.000,BURLINGTON RESOURCES O&G CO LP,NIOBRARA,DENVER BASIN,COLORADO,ARAPAHOE,39.684606,-104.642128,39.68445,-104.60557,9005.0,994.6866,591.800400
1,5123377130000,2013-07-21,2013-10-06,2014-02-26,2014-02-01 00:00:00.000,SRC ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.509320,-104.780980,40.49692,-104.77859,4195.0,991.5857,628.632100
2,5123379280000,2013-09-08,2013-09-25,2014-09-07,2013-11-01 00:00:00.000,BONANZA CREEK ENERGY OPERATING CO LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.335390,-104.363000,40.34780,-104.36863,4273.0,1000.2760,564.484100
3,5123379400000,2013-09-11,2014-12-05,2015-03-31,2015-03-01 00:00:00.000,NOBLE ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.152220,-104.530780,40.17445,-104.52932,7078.0,973.4437,824.002000
4,5123385820100,2014-01-07,2014-01-13,2014-04-23,2014-04-01 00:00:00.000,GREAT WESTERN OPERATING COMPANY LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.508303,-104.868180,40.49558,-104.86757,3211.0,783.5919,603.141400
5,5123390320000,2014-02-27,2014-06-20,2014-10-30,2014-10-01 00:00:00.000,NOBLE ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.520989,-104.450861,40.52100,-104.46772,4259.0,1011.0440,698.681900
6,5123390440000,2014-02-28,2014-04-26,2014-08-16,2014-08-01 00:00:00.000,KERR-MCGEE OIL & GAS ONSHORE LP,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.118872,-104.789372,40.13079,-104.78716,4518.0,469.8262,798.167600
7,5123392690000,2014-04-14,2015-03-20,2015-08-03,2015-07-01 00:00:00.000,CRESTONE PEAK RESOURCES OPERATING LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.147015,-104.898342,40.16105,-104.89340,4975.0,1267.8870,835.992800
8,5123399750000,2014-08-09,2014-11-14,2015-04-16,2015-04-01 00:00:00.000,KERR-MCGEE OIL & GAS ONSHORE LP,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.263373,-104.727955,40.27426,-104.73307,4786.0,805.9642,1133.333000
9,5123402600000,2014-09-22,2015-06-16,2015-09-13,2015-09-01 00:00:00.000,EXTRACTION OIL & GAS LLC,CODELL,DENVER BASIN,COLORADO,WELD,40.353967,-104.944679,40.35440,-104.96173,4195.0,926.5010,403.322300
10,5123409020000,2014-12-23,2015-02-07,2015-09-07,2015-09-01 00:00:00.000,NOBLE ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.482361,-104.468261,40.48424,-104.45072,4240.0,697.0967,983.059900
11,5123410480000,2015-01-21,2015-03-16,2015-04-23,2015-04-01 00:00:00.000,BONANZA CREEK ENERGY OPERATING CO LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.433139,-104.298585,40.43460,-104.28176,4294.0,896.9146,604.394700
12,30015414470000,2013-06-07,2013-10-06,2014-01-07,2013-12-01 00:00:00.000,OXY USA INC,BONE SPRING,PERMIAN BASIN,NEW MEXICO,EDDY,32.312443,-104.030511,32.31051,-104.01594,3790.0,648.1232,477.618100
13,30025425390000,2015-04-30,2015-06-17,2015-10-10,2015-08-01 00:00:00.000,EOG RESOURCES INCORPORATED,WOLFCAMP UPPER,PERMIAN BASIN,NEW MEXICO,LEA,32.080410,-103.530040,32.09347,-103.52959,4583.0,1657.9800,1625.025000
14,33023010960000,2013-08-22,2014-01-19,2014-04-07,2014-03-01 00:00:00.000,PETRO-HUNT LLC,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,DIVIDE,48.893759,-103.647074,48.86601,-103.64545,10055.0,247.5587,193.152500
15,33025026780000,2014-09-30,2015-05-04,2015-09-23,2015-08-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,DUNN,47.457199,-102.876301,47.48709,-102.87709,10225.0,326.3353,763.942100
16,33053048870100,2013-03-21,2014-08-06,2014-11-05,2014-11-01 00:00:00.000,OASIS PETROLEUM NORTH AMERICA LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.995019,-103.561306,47.99470,-103.52035,9400.0,984.4741,559.110700
17,33053051530000,2013-07-29,2013-09-03,2014-04-27,2014-04-01 00:00:00.000,BURLINGTON RESOURCES O&G CO LP,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.992928,-103.020490,48.02321,-103.01697,10415.0,341.2530,233.851900
18,33053056390200,2014-01-23,2014-12-18,2015-01-17,2015-01-01 00:00:00.000,NEWFIELD PRODUCTION COMPANY,THREE FORKS / BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,48.067984,-103.032125,48.08104,-103.03132,1513.0,455.8970,367.239100
19,33053056550000,2014-01-28,2014-03-14,2014-06-25,2014-06-01 00:00:00.000,NINE POINT ENERGY LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.791114,-103.545864,47.81872,-103.54224,9613.0,392.4996,400.888700
20,33053059400000,2014-05-15,2014-11-13,2015-04-03,2015-03-01 00:00:00.000,XTO ENERGY INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.746094,-103.098475,47.71838,-103.09252,10021.0,375.7643,361.355000
21,33053061530000,2014-08-05,2015-01-27,2015-06-28,2015-06-01 00:00:00.000,BURLINGTON RESOURCES O&G CO LP,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.846022,-102.967045,47.81920,-102.96232,9291.0,440.1811,279.032700
22,33053061600000,2014-08-05,2014-09-25,2015-01-13,2014-12-01 00:00:00.000,HESS BAKKEN INVESTMENTS II LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.675447,-103.316278,47.70267,-103.31067,10052.0,148.4382,119.386300
23,33053061970000,2014-08-15,2015-02-25,2015-08-10,2015-08-01 00:00:00.000,HESS BAKKEN INVESTMENTS II LLC,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.920949,-102.856899,47.92118,-102.81310,9841.0,354.8798,240.360000
24,33053062710000,2014-09-15,2014-11-02,2015-04-05,2015-03-01 00:00:00.000,WHITING OIL & GAS CORPORATION,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.847589,-103.975208,47.82010,-103.98625,10951.0,286.4915,236.736400
25,33053067490000,2015-02-23,2015-07-09,2015-10-10,2015-10-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,48.022461,-103.109486,47.99290,-103.10193,11238.0,401.0879,174.951200
26,33061032390000,2014-08-05,2014-10-14,2015-02-16,2015-02-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MOUNTRAIL,48.109905,-102.565508,48.09766,-102.54984,5102.0,307.2087,474.892600
27,33061033560000,2014-10-16,2015-02-06,2015-07-24,2015-07-01 00:00:00.000,HESS BAKKEN INVESTMENTS II LLC,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MOUNTRAIL,48.140773,-102.694397,48.11112,-102.69618,9872.0,206.0430,161.287500
28,33105031270000,2013-07-16,2013-09-19,2014-02-10,2014-02-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.167886,-103.193273,48.14049,-103.18976,9211.0,366.1146,3.051352
29,33105032030000,2013-09-09,2013-10-24,2014-04-26,2014-04-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.230954,-103.189569,48.19827,-103.19005,11492.0,359.6471,301.821500
30,33105034810000,2014-03-24,2014-06-06,2015-01-15,2014-12-01 00:00:00.000,XTO ENERGY INCORPORATED,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.516578,-102.938572,48.49633,-102.93151,7143.0,346.7994,394.368900
31,33105035380000,2014-05-23,2014-06-11,2014-12-29,2014-12-01 00:00:00.000,LIBERTY RESOURCES MANAGEMENT COMPANY LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.503628,-102.977092,48.53119,-102.97815,9947.0,422.7651,815.382500
32,33105035810000,2014-06-19,2014-09-01,2015-05-13,2015-03-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.603374,-103.032381,48.57598,-103.03142,9521.0,333.2274,256.376800
33,33105036550100,2014-08-04,2014-10-27,2015-02-26,2015-02-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.112097,-103.294476,48.13924,-103.29261,4542.0,330.9360,231.485800
34,33105037690100,2014-09-22,2014-12-23,2015-05-08,2015-03-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.225953,-103.318167,48.19845,-103.31350,9477.0,610.1913,517.700600
35,35017246780000,2014-03-19,2014-03-21,2014-05-19,2014-06-01 00:00:00.000,MARATHON OIL COMPANY,WOODFORD,ANADARKO BASIN,OKLAHOMA,CANADIAN,35.550467,-97.837858,35.53706,-97.83706,4596.0,1294.5750,1924.085000
36,35017246960000,2014-09-03,2014-09-28,2014-12-10,2014-12-01 00:00:00.000,CIMAREX ENERGY COMPANY,WOODFORD,ANADARKO BASIN,OKLAHOMA,CANADIAN,35.383976,-97.991358,35.40532,-97.99148,7440.0,2053.6050,1768.781000
37,35073250300000,2014-11-26,2015-02-14,2015-08-25,2015-08-01 00:00:00.000,CHAPARRAL ENERGY LIMITED LIABILITY CORP,OSWEGO,ANADARKO BASIN,OKLAHOMA,KINGFISHER,36.044720,-97.893227,36.03002,-97.89306,4530.0,108.3326,382.215800
38,42105419830000,2014-02-27,2014-03-03,2014-06-04,2014-06-01 00:00:00.000,APPROACH OPERATING LIMITED LIABILITY CORP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,30.932566,-101.224790,30.91022,-101.22338,7330.0,1201.4860,1170.349000
39,42105420060100,2014-04-10,2014-06-07,2014-08-04,2014-08-01 00:00:00.000,EP ENERGY E&P COMPANY LP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,31.036220,-101.298203,31.05840,-101.29816,7727.0,1322.0210,928.173800
40,42105421020000,2014-08-16,2014-08-23,2014-12-22,2014-12-01 00:00:00.000,APPROACH OPERATING LIMITED LIABILITY CORP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,30.931085,-101.275646,30.91015,-101.27472,6853.0,1247.4980,1382.348000
41,42105421500000,2014-10-07,2014-11-23,2015-03-29,2015-03-01 00:00:00.000,APPROACH OPERATING LIMITED LIABILITY CORP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,30.891880,-101.239248,30.91010,-101.23926,5946.0,1182.1640,1441.936000
42,42301318440000,2012-09-13,2012-11-15,2014-01-27,2013-04-01 00:00:00.000,SHELL WESTERN E & P INCORPORATED LP,BONE SPRING,PERMIAN BASIN,TEXAS,LOVING,31.955840,-103.740776,31.94281,-103.74097,3656.0,488.5271,354.653600
43,42317401950000,2015-05-18,2015-06-23,2015-10-06,2015-10-01 00:00:00.000,PIONEER NATURAL RESOURCES USA INC,SPRABERRY,PERMIAN BASIN,TEXAS,MARTIN,32.175802,-102.062501,32.19690,-102.06904,7290.0,1157.6290,1560.677000
44,42371392130100,2014-06-27,2014-08-13,2014-12-01,2014-11-01 00:00:00.000,DIAMONDBACK EXPLORATION & PROD LLC,WOLFCAMP,PERMIAN BASIN,TEXAS,PECOS,31.103318,-103.107997,31.10177,-103.13352,7664.0,1785.7310,3272.875000
45,42383381710000,2013-01-09,2013-10-23,2014-03-07,2014-02-01 00:00:00.000,SABLE PERMIAN RESOURCES LAND LLC,WOLFCAMP,PERMIAN BASIN,TEXAS,REAGAN,31.287603,-101.589564,31.25907,-101.58952,9619.0,1659.3060,1489.541000
46,42389339940000,2013-11-04,2014-02-03,2014-07-16,2014-06-01 00:00:00.000,EOG RESOURCES INCORPORATED,WOLFCAMP,PERMIAN BASIN,TEXAS,REEVES,31.613055,-103.943273,31.59780,-103.94402,4808.0,1535.0170,1263.295000
47,42389345710000,2014-10-06,2014-11-30,2015-03-31,2015-03-01 00:00:00.000,BHP BILLITON PETROLEUM(TXLA OP) COMPANY,WOLFCAMP,PERMIAN BASIN,TEXAS,REEVES,31.767678,-103.855621,31.78125,-103.85369,4738.0,1319.8350,1201.862000
48,42461395750000,2014-09-17,2014-11-07,2015-06-07,2015-06-01 00:00:00.000,PIONEER NATURAL RESOURCES USA INC,SPRABERRY,PERMIAN BASIN,TEXAS,UPTON,31.268789,-101.789362,31.24249,-101.78967,9091.0,983.5690,1691.322000
49,49021210550000,2013-11-13,2014-01-10,2014-05-19,2014-03-01 00:00:00.000,SAMSON EXPLORATION LLC,CODELL,DENVER BASIN,WYOMING,LARAMIE,41.289530,-104.662340,41.27109,-104.66166,6030.0,1106.8640,652.499000

In [99]:
wells_info_df['CompletionDate'] = pd.to_datetime(wells_info_df['CompletionDate'])
wells_info_df['FirstProductionDate'] = pd.to_datetime(wells_info_df['FirstProductionDate'])
diff = np.floor((wells_info_df['CompletionDate'] - wells_info_df['FirstProductionDate']).dt.days / 30)
diff[diff < 0] = 0
diff_df = pd.DataFrame(diff,columns = ['Prod_duration'])
pd.concat([wells_info_df['API'],diff], axis=1)

               API     0
0    5005072170100   1.0
1    5123377130000   0.0
2    5123379280000  10.0
3    5123379400000   1.0
4    5123385820100   0.0
5    5123390320000   0.0
6    5123390440000   0.0
7    5123392690000   1.0
8    5123399750000   0.0
9    5123402600000   0.0
10   5123409020000   0.0
11   5123410480000   0.0
12  30015414470000   1.0
13  30025425390000   2.0
14  33023010960000   1.0
15  33025026780000   1.0
16  33053048870100   0.0
17  33053051530000   0.0
18  33053056390200   0.0
19  33053056550000   0.0
20  33053059400000   1.0
21  33053061530000   0.0
22  33053061600000   1.0
23  33053061970000   0.0
24  33053062710000   1.0
25  33053067490000   0.0
26  33061032390000   0.0
27  33061033560000   0.0
28  33105031270000   0.0
29  33105032030000   0.0
30  33105034810000   1.0
31  33105035380000   0.0
32  33105035810000   2.0
33  33105036550100   0.0
34  33105037690100   2.0
35  35017246780000   0.0
36  35017246960000   0.0
37  35073250300000   0.0
38  42105419830000   0.0
39  42105420060100   0.0
40  42105421020000   0.0
41  42105421500000   0.0
42  42301318440000  10.0
43  42317401950000   0.0
44  42371392130100   1.0
45  42383381710000   1.0
46  42389339940000   1.0
47  42389345710000   1.0
48  42461395750000   0.0
49  49021210550000   2.0

3.Fill

In [137]:
wells_info_na_df = pd.read_csv('wells_info_na.csv')
wells_info_na_df

,API,CompletionDate,FirstProductionDate,formation,BasinName,StateName,CountyName,LatWGS84,LonWGS84,PROP_PER_FOOT
0,5123402600000,2015-09-13,2015-09-01 00:00:00.000,CODELL,DENVER BASIN,COLORADO,WELD,40.353967,-104.944679,926.5010
1,5123409020000,2015-09-07,2015-09-01 00:00:00.000,NIOBRARA,NaN,COLORADO,WELD,40.482361,-104.468261,697.0967
2,5123410480000,NaN,2015-04-01 00:00:00.000,NIOBRARA,DENVER BASIN,NaN,WELD,NaN,NaN,896.9146
3,30015414470000,2014-01-07,2013-12-01 00:00:00.000,BONE SPRING,PERMIAN BASIN,NEW MEXICO,EDDY,NaN,NaN,648.1232
4,30025425390000,2015-10-10,2015-08-01 00:00:00.000,WOLFCAMP UPPER,PERMIAN BASIN,NEW MEXICO,LEA,32.080410,-103.530040,1657.9800
5,33053048870100,2014-11-05,2014-11-01 00:00:00.000,BAKKEN,NaN,NORTH DAKOTA,MCKENZIE,47.995019,-103.561306,984.4741
6,33053051530000,2014-04-27,2014-04-01 00:00:00.000,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.992928,-103.020490,341.2530

In [139]:
wells_info_na_df = wells_info_na_df.fillna(wells_info_na_df.median())
columns = list(wells_info_na_df)
for i in columns:
    wells_info_na_df[i] = wells_info_na_df[i].fillna(wells_info_na_df[i].value_counts().index[0])
wells_info_na_df

,API,CompletionDate,FirstProductionDate,formation,BasinName,StateName,CountyName,LatWGS84,LonWGS84,PROP_PER_FOOT
0,5123402600000,2015-09-13,2015-09-01 00:00:00.000,CODELL,DENVER BASIN,COLORADO,WELD,40.353967,-104.944679,926.5010
1,5123409020000,2015-09-07,2015-09-01 00:00:00.000,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.482361,-104.468261,697.0967
2,5123410480000,2015-09-07,2015-04-01 00:00:00.000,NIOBRARA,DENVER BASIN,NORTH DAKOTA,WELD,40.482361,-103.561306,896.9146
3,30015414470000,2014-01-07,2013-12-01 00:00:00.000,BONE SPRING,PERMIAN BASIN,NEW MEXICO,EDDY,40.482361,-103.561306,648.1232
4,30025425390000,2015-10-10,2015-08-01 00:00:00.000,WOLFCAMP UPPER,PERMIAN BASIN,NEW MEXICO,LEA,32.080410,-103.530040,1657.9800
5,33053048870100,2014-11-05,2014-11-01 00:00:00.000,BAKKEN,DENVER BASIN,NORTH DAKOTA,MCKENZIE,47.995019,-103.561306,984.4741
6,33053051530000,2014-04-27,2014-04-01 00:00:00.000,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.992928,-103.020490,341.2530

4.Add column

In [140]:
production_df = pd.read_csv('production.csv')

In [206]:
tmp = production_df.groupby('API').sum()[['Liquid','Gas','Water']].sum(axis = 1)
df_summ = pd.DataFrame(tmp,columns = ['Debit'])
groups = pd.DataFrame(production_df.groupby('API').head(12))
tmp = groups.groupby('API').sum()[['Liquid','Gas','Water']].sum(axis = 1)
df_summ_12m = pd.DataFrame(tmp,columns = ['Debit_12m'])
wells_info_df = pd.merge(wells_info_df,df_summ,on='API')
pd.merge(wells_info_df,df_summ_12m,on='API')

,API,PermitDate,SpudDate,CompletionDate,FirstProductionDate,operatorNameIHS,formation,BasinName,StateName,CountyName,LatWGS84,LonWGS84,BottomHoleLatitude,BottomHoleLongitude,LATERAL_LENGTH_BLEND,PROP_PER_FOOT,WATER_PER_FOOT,Debit,Debit_12m
0,5005072170100,2014-05-06,2014-05-06,2014-12-02,2014-11-01 00:00:00.000,BURLINGTON RESOURCES O&G CO LP,NIOBRARA,DENVER BASIN,COLORADO,ARAPAHOE,39.684606,-104.642128,39.68445,-104.60557,9005.0,994.6866,591.800400,629543,393066
1,5123377130000,2013-07-21,2013-10-06,2014-02-26,2014-02-01 00:00:00.000,SRC ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.509320,-104.780980,40.49692,-104.77859,4195.0,991.5857,628.632100,176949,110847
2,5123379280000,2013-09-08,2013-09-25,2014-09-07,2013-11-01 00:00:00.000,BONANZA CREEK ENERGY OPERATING CO LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.335390,-104.363000,40.34780,-104.36863,4273.0,1000.2760,564.484100,239200,152298
3,5123379400000,2013-09-11,2014-12-05,2015-03-31,2015-03-01 00:00:00.000,NOBLE ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.152220,-104.530780,40.17445,-104.52932,7078.0,973.4437,824.002000,464291,317982
4,5123385820100,2014-01-07,2014-01-13,2014-04-23,2014-04-01 00:00:00.000,GREAT WESTERN OPERATING COMPANY LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.508303,-104.868180,40.49558,-104.86757,3211.0,783.5919,603.141400,104618,74479
5,5123390320000,2014-02-27,2014-06-20,2014-10-30,2014-10-01 00:00:00.000,NOBLE ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.520989,-104.450861,40.52100,-104.46772,4259.0,1011.0440,698.681900,194913,122927
6,5123390440000,2014-02-28,2014-04-26,2014-08-16,2014-08-01 00:00:00.000,KERR-MCGEE OIL & GAS ONSHORE LP,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.118872,-104.789372,40.13079,-104.78716,4518.0,469.8262,798.167600,625002,345346
7,5123392690000,2014-04-14,2015-03-20,2015-08-03,2015-07-01 00:00:00.000,CRESTONE PEAK RESOURCES OPERATING LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.147015,-104.898342,40.16105,-104.89340,4975.0,1267.8870,835.992800,430559,213662
8,5123399750000,2014-08-09,2014-11-14,2015-04-16,2015-04-01 00:00:00.000,KERR-MCGEE OIL & GAS ONSHORE LP,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.263373,-104.727955,40.27426,-104.73307,4786.0,805.9642,1133.333000,914341,464570
9,5123402600000,2014-09-22,2015-06-16,2015-09-13,2015-09-01 00:00:00.000,EXTRACTION OIL & GAS LLC,CODELL,DENVER BASIN,COLORADO,WELD,40.353967,-104.944679,40.35440,-104.96173,4195.0,926.5010,403.322300,585025,289323
10,5123409020000,2014-12-23,2015-02-07,2015-09-07,2015-09-01 00:00:00.000,NOBLE ENERGY INCORPORATED,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.482361,-104.468261,40.48424,-104.45072,4240.0,697.0967,983.059900,386079,243576
11,5123410480000,2015-01-21,2015-03-16,2015-04-23,2015-04-01 00:00:00.000,BONANZA CREEK ENERGY OPERATING CO LLC,NIOBRARA,DENVER BASIN,COLORADO,WELD,40.433139,-104.298585,40.43460,-104.28176,4294.0,896.9146,604.394700,175006,126798
12,30015414470000,2013-06-07,2013-10-06,2014-01-07,2013-12-01 00:00:00.000,OXY USA INC,BONE SPRING,PERMIAN BASIN,NEW MEXICO,EDDY,32.312443,-104.030511,32.31051,-104.01594,3790.0,648.1232,477.618100,337427,187264
13,30025425390000,2015-04-30,2015-06-17,2015-10-10,2015-08-01 00:00:00.000,EOG RESOURCES INCORPORATED,WOLFCAMP UPPER,PERMIAN BASIN,NEW MEXICO,LEA,32.080410,-103.530040,32.09347,-103.52959,4583.0,1657.9800,1625.025000,1125368,710613
14,33023010960000,2013-08-22,2014-01-19,2014-04-07,2014-03-01 00:00:00.000,PETRO-HUNT LLC,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,DIVIDE,48.893759,-103.647074,48.86601,-103.64545,10055.0,247.5587,193.152500,364179,245390
15,33025026780000,2014-09-30,2015-05-04,2015-09-23,2015-08-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,DUNN,47.457199,-102.876301,47.48709,-102.87709,10225.0,326.3353,763.942100,626167,403658
16,33053048870100,2013-03-21,2014-08-06,2014-11-05,2014-11-01 00:00:00.000,OASIS PETROLEUM NORTH AMERICA LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.995019,-103.561306,47.99470,-103.52035,9400.0,984.4741,559.110700,651306,481200
17,33053051530000,2013-07-29,2013-09-03,2014-04-27,2014-04-01 00:00:00.000,BURLINGTON RESOURCES O&G CO LP,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.992928,-103.020490,48.02321,-103.01697,10415.0,341.2530,233.851900,996667,533255
18,33053056390200,2014-01-23,2014-12-18,2015-01-17,2015-01-01 00:00:00.000,NEWFIELD PRODUCTION COMPANY,THREE FORKS / BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,48.067984,-103.032125,48.08104,-103.03132,1513.0,455.8970,367.239100,397768,282199
19,33053056550000,2014-01-28,2014-03-14,2014-06-25,2014-06-01 00:00:00.000,NINE POINT ENERGY LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.791114,-103.545864,47.81872,-103.54224,9613.0,392.4996,400.888700,396225,277990
20,33053059400000,2014-05-15,2014-11-13,2015-04-03,2015-03-01 00:00:00.000,XTO ENERGY INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.746094,-103.098475,47.71838,-103.09252,10021.0,375.7643,361.355000,428793,251788
21,33053061530000,2014-08-05,2015-01-27,2015-06-28,2015-06-01 00:00:00.000,BURLINGTON RESOURCES O&G CO LP,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.846022,-102.967045,47.81920,-102.96232,9291.0,440.1811,279.032700,511759,320915
22,33053061600000,2014-08-05,2014-09-25,2015-01-13,2014-12-01 00:00:00.000,HESS BAKKEN INVESTMENTS II LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.675447,-103.316278,47.70267,-103.31067,10052.0,148.4382,119.386300,221910,142184
23,33053061970000,2014-08-15,2015-02-25,2015-08-10,2015-08-01 00:00:00.000,HESS BAKKEN INVESTMENTS II LLC,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.920949,-102.856899,47.92118,-102.81310,9841.0,354.8798,240.360000,486190,350423
24,33053062710000,2014-09-15,2014-11-02,2015-04-05,2015-03-01 00:00:00.000,WHITING OIL & GAS CORPORATION,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,47.847589,-103.975208,47.82010,-103.98625,10951.0,286.4915,236.736400,253455,179026
25,33053067490000,2015-02-23,2015-07-09,2015-10-10,2015-10-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MCKENZIE,48.022461,-103.109486,47.99290,-103.10193,11238.0,401.0879,174.951200,1681212,964484
26,33061032390000,2014-08-05,2014-10-14,2015-02-16,2015-02-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MOUNTRAIL,48.109905,-102.565508,48.09766,-102.54984,5102.0,307.2087,474.892600,231549,166712
27,33061033560000,2014-10-16,2015-02-06,2015-07-24,2015-07-01 00:00:00.000,HESS BAKKEN INVESTMENTS II LLC,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,MOUNTRAIL,48.140773,-102.694397,48.11112,-102.69618,9872.0,206.0430,161.287500,386651,276233
28,33105031270000,2013-07-16,2013-09-19,2014-02-10,2014-02-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.167886,-103.193273,48.14049,-103.18976,9211.0,366.1146,3.051352,376506,267798
29,33105032030000,2013-09-09,2013-10-24,2014-04-26,2014-04-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.230954,-103.189569,48.19827,-103.19005,11492.0,359.6471,301.821500,509890,344966
30,33105034810000,2014-03-24,2014-06-06,2015-01-15,2014-12-01 00:00:00.000,XTO ENERGY INCORPORATED,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.516578,-102.938572,48.49633,-102.93151,7143.0,346.7994,394.368900,227643,125052
31,33105035380000,2014-05-23,2014-06-11,2014-12-29,2014-12-01 00:00:00.000,LIBERTY RESOURCES MANAGEMENT COMPANY LLC,BAKKEN,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.503628,-102.977092,48.53119,-102.97815,9947.0,422.7651,815.382500,929340,605942
32,33105035810000,2014-06-19,2014-09-01,2015-05-13,2015-03-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.603374,-103.032381,48.57598,-103.03142,9521.0,333.2274,256.376800,379905,246325
33,33105036550100,2014-08-04,2014-10-27,2015-02-26,2015-02-01 00:00:00.000,WHITING OIL & GAS CORPORATION,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.112097,-103.294476,48.13924,-103.29261,4542.0,330.9360,231.485800,445145,319502
34,33105037690100,2014-09-22,2014-12-23,2015-05-08,2015-03-01 00:00:00.000,CONTINENTAL RESOURCES INCORPORATED,THREE FORKS,WILLISTON BASIN,NORTH DAKOTA,WILLIAMS,48.225953,-103.318167,48.19845,-103.31350,9477.0,610.1913,517.700600,717879,403726
35,35017246780000,2014-03-19,2014-03-21,2014-05-19,2014-06-01 00:00:00.000,MARATHON OIL COMPANY,WOODFORD,ANADARKO BASIN,OKLAHOMA,CANADIAN,35.550467,-97.837858,35.53706,-97.83706,4596.0,1294.5750,1924.085000,437854,263877
36,35017246960000,2014-09-03,2014-09-28,2014-12-10,2014-12-01 00:00:00.000,CIMAREX ENERGY COMPANY,WOODFORD,ANADARKO BASIN,OKLAHOMA,CANADIAN,35.383976,-97.991358,35.40532,-97.99148,7440.0,2053.6050,1768.781000,1291277,729420
37,35073250300000,2014-11-26,2015-02-14,2015-08-25,2015-08-01 00:00:00.000,CHAPARRAL ENERGY LIMITED LIABILITY CORP,OSWEGO,ANADARKO BASIN,OKLAHOMA,KINGFISHER,36.044720,-97.893227,36.03002,-97.89306,4530.0,108.3326,382.215800,184587,106435
38,42105419830000,2014-02-27,2014-03-03,2014-06-04,2014-06-01 00:00:00.000,APPROACH OPERATING LIMITED LIABILITY CORP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,30.932566,-101.224790,30.91022,-101.22338,7330.0,1201.4860,1170.349000,434697,276783
39,42105420060100,2014-04-10,2014-06-07,2014-08-04,2014-08-01 00:00:00.000,EP ENERGY E&P COMPANY LP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,31.036220,-101.298203,31.05840,-101.29816,7727.0,1322.0210,928.173800,513707,365612
40,42105421020000,2014-08-16,2014-08-23,2014-12-22,2014-12-01 00:00:00.000,APPROACH OPERATING LIMITED LIABILITY CORP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,30.931085,-101.275646,30.91015,-101.27472,6853.0,1247.4980,1382.348000,992229,810097
41,42105421500000,2014-10-07,2014-11-23,2015-03-29,2015-03-01 00:00:00.000,APPROACH OPERATING LIMITED LIABILITY CORP,WOLFCAMP,PERMIAN BASIN,TEXAS,CROCKETT,30.891880,-101.239248,30.91010,-101.23926,5946.0,1182.1640,1441.936000,499938,332774
42,42301318440000,2012-09-13,2012-11-15,2014-01-27,2013-04-01 00:00:00.000,SHELL WESTERN E & P INCORPORATED LP,BONE SPRING,PERMIAN BASIN,TEXAS,LOVING,31.955840,-103.740776,31.94281,-103.74097,3656.0,488.5271,354.653600,452449,386879
43,42317401950000,2015-05-18,2015-06-23,2015-10-06,2015-10-01 00:00:00.000,PIONEER NATURAL RESOURCES USA INC,SPRABERRY,PERMIAN BASIN,TEXAS,MARTIN,32.175802,-102.062501,32.19690,-102.06904,7290.0,1157.6290,1560.677000,515298,431774
44,42371392130100,2014-06-27,2014-08-13,2014-12-01,2014-11-01 00:00:00.000,DIAMONDBACK EXPLORATION & PROD LLC,WOLFCAMP,PERMIAN BASIN,TEXAS,PECOS,31.103318,-103.107997,31.10177,-103.13352,7664.0,1785.7310,3272.875000,645819,386538
45,42383381710000,2013-01-09,2013-10-23,2014-03-07,2014-02-01 00:00:00.000,SABLE PERMIAN RESOURCES LAND LLC,WOLFCAMP,PERMIAN BASIN,TEXAS,REAGAN,31.287603,-101.589564,31.25907,-101.58952,9619.0,1659.3060,1489.541000,476062,297571
46,42389339940000,2013-11-04,2014-02-03,2014-07-16,2014-06-01 00:00:00.000,EOG RESOURCES INCORPORATED,WOLFCAMP,PERMIAN BASIN,TEXAS,REEVES,31.613055,-103.943273,31.59780,-103.94402,4808.0,1535.0170,1263.295000,1630885,1025479
47,42389345710000,2014-10-06,2014-11-30,2015-03-31,2015-03-01 00:00:00.000,BHP BILLITON PETROLEUM(TXLA OP) COMPANY,WOLFCAMP,PERMIAN BASIN,TEXAS,REEVES,31.767678,-103.855621,31.78125,-103.85369,4738.0,1319.8350,1201.862000,2273531,1685928
48,42461395750000,2014-09-17,2014-11-07,2015-06-07,2015-06-01 00:00:00.000,PIONEER NATURAL RESOURCES USA INC,SPRABERRY,PERMIAN BASIN,TEXAS,UPTON,31.268789,-101.789362,31.24249,-101.78967,9091.0,983.5690,1691.322000,622475,420637
49,49021210550000,2013-11-13,2014-01-10,2014-05-19,2014-03-01 00:00:00.000,SAMSON EXPLORATION LLC,CODELL,DENVER BASIN,WYOMING,LARAMIE,41.289530,-104.662340,41.27109,-104.66166,6030.0,1106.8640,652.499000,162041,128064